permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", "README.md", "Rakefile"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

title : RJ722#blog
author :
  name : Rahul Jha
  email : rahul722j@gmail.com

production_url : https://rj722.github.io/

gems:
  - jekyll-redirect-from
